# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aitvwqazoak8GB02KRFIjaRf36yFVgm+KCYQzoYbTm+8BEtwGjVM0KIqW0eU2AXhlT3smuzdKN/+bGOUvevtkzIjyOEwmtxuWVZs1AS/fVQgBFeyiXDKZx4T7VvmDRG//p5u5HHempcmXIQ9/AHLvNKQ4bCiYx0vCMu3CVijpCR1G4DHmh+7Gtp68nEQZZa4iSsVDDKDa/i6mTzp8hXGZiN2MJZZcY/l+JXYQoaKlqJJoWnzyk7jYR3dXZT8TwQ78tPN5EZgMwW7Maw/9PYwDAQ/bf1rQc9mZAJlv9bfnhhxSCqy7IOejssAh0HF2XS1iCSuhOSnaGVZTVERYlb0aTSupphfxbxPgTjmqNyh8IfP6PpLHzwTLiZaF9spJBhp5eDiPE7DKqvVt0GFcvDaaiKuAe/PNE+zaxk/z1109Dm+6yNnHLH4z89DBsUbxro8Wqv9jv++GdWu2sbFA4IXw747SQy32gD2nV+Kz/SFvuJAaGPDfFY0amhfzxl0BM/xD+bm85knU+8DXNrMvkeVufHIvYEN2zEhR9xxrD2UxOSGTzxaxluUvV0mkyGJ2dn9tLg+ayQwpXsA8AiQJdKZPkU0dkh5LcmbUdUvsZzhz92ZFiWgU9LqmpIw50y42fXaX0rhDm2UtVVvAhOAv6811DhuF/3TVxo6pMkelfF+0UM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml