travis:
  secure:
    BINSTAR_TOKEN: aitvwqazoak8GB02KRFIjaRf36yFVgm+KCYQzoYbTm+8BEtwGjVM0KIqW0eU2AXhlT3smuzdKN/+bGOUvevtkzIjyOEwmtxuWVZs1AS/fVQgBFeyiXDKZx4T7VvmDRG//p5u5HHempcmXIQ9/AHLvNKQ4bCiYx0vCMu3CVijpCR1G4DHmh+7Gtp68nEQZZa4iSsVDDKDa/i6mTzp8hXGZiN2MJZZcY/l+JXYQoaKlqJJoWnzyk7jYR3dXZT8TwQ78tPN5EZgMwW7Maw/9PYwDAQ/bf1rQc9mZAJlv9bfnhhxSCqy7IOejssAh0HF2XS1iCSuhOSnaGVZTVERYlb0aTSupphfxbxPgTjmqNyh8IfP6PpLHzwTLiZaF9spJBhp5eDiPE7DKqvVt0GFcvDaaiKuAe/PNE+zaxk/z1109Dm+6yNnHLH4z89DBsUbxro8Wqv9jv++GdWu2sbFA4IXw747SQy32gD2nV+Kz/SFvuJAaGPDfFY0amhfzxl0BM/xD+bm85knU+8DXNrMvkeVufHIvYEN2zEhR9xxrD2UxOSGTzxaxluUvV0mkyGJ2dn9tLg+ayQwpXsA8AiQJdKZPkU0dkh5LcmbUdUvsZzhz92ZFiWgU9LqmpIw50y42fXaX0rhDm2UtVVvAhOAv6811DhuF/3TVxo6pMkelfF+0UM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
